### ISSUE TITLE
Customization of GeoNode

### ISSUE THREAD

**Issue by chpicone** [geosolutions-it/krihs-geonode#2]
We need to customize GeoNode: 
- [ ] logo
- [ ] any colors preferences
- [ ] image in high resolution for the background
- [ ] a blurb for the about section
We can get inspired by: https://geonode.wfp.org
[Slide provided by the customer](https://app.zenhub.com/files/321667805/6abedd45-997c-4526-bc9b-830bd77d4a04/download)

**Comment by allyoucanmap** [comment]
@chpicone Update the PR with all improvements for the theme customization
